# run: conda env create --file environment.yml

name: nlp
channels:
  - conda-forge
dependencies:
  - python=3.7
  - spacy
  - spacy-lookups-data
  - spacy-model-en_core_web_sm
  - spacy
  - jupyterlab
  - pip
  - nltk
  - pip:
      - https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.2.0/en_core_web_sm-2.2.0.tar.gz
      - https://storage.googleapis.com/spacy-pl-public-models/pl_model-1.0.0.tar.gz
